### PR TITLE
Set div => false as default

### PR DESCRIPTION
**Pull request by ae-bogdan**

### CODE REVIEW

**Comment by ae-bogdan** [comment]
@dereuromark please check

**Comment by dereuromark** [comment]
What's the reason for this?

**Comment by ae-bogdan** [comment]
In cake2 when no `div` tag is set, the default is for inputs to be surrounded in a div. However in cake 3 this is not the case.

**Comment by dereuromark** [comment]
I am not fully sure if we should switch this at this late point in time
But i don't use 2.x anymore, so if everyone else is fine with this, we can merge.

**Comment by ae-bogdan** [comment]
I dropped the condition, so now the `div` should be exactly like it is in cake 3. I'm sure whoever uses this shim would rather deal with this problem before they migrate to cake 3.

**Pull request merged**
