### PR TITLE
Cake4

### PR DESCRIPTION
**Pull request by dereuromark**
4.x branch, wont be merged yet, but to track more easily the shims going in.

### CODE REVIEW

**Comment by dereuromark** [comment]
@ADmad Do you know how to fix the now failing tests with FormHelper?

**Comment by ADmad** [comment]
For `FormHelperTest::testDateTimeSecured` and `FormHelperTest::testDateTimeSecuredDisabled` failures I would guess you'll have to update them as per changes in core as the FormHelper now uses the `FormProtector` class to generate security token.

**Comment by dereuromark** [comment]
Those I would agree and I can look into

The other one looks like a regression in 4.x and empty value suddenly being injected and selected for some reason:

    <option value="" selected="selected"></option><option value="2001">2001</option>

**Comment by dereuromark** [comment]
Setting `empty` to false makes it go away. Is this intentional?

**Pull request merged**
